### ISSUE TITLE
AddToESFunction Error / No data loaded

### ISSUE THREAD

**Issue by HerschelC** [jbesw/s3-to-lambda#1]
I completed all the steps and was excited to run the post from Postman.. received 0 results. I did some investigation through the Cloudwatch logs and see that every call from AddToESFunction has the below error:

Error: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: https. is not in the cert's altnames: DNS:*.us-east-1.es.amazonaws.com

ERROR	Handler error: undefined

The ES cluster health also reports all InvalidHostHeaderRequests as the Lambda function attempts to connect.

**Comment by HerschelC** [comment]
The problem was when I added the endpoint for ES. I just copied and pasted from the ES search console - which included the https:// at the beginning of the endpoint. Removed that and it works now.

**Comment by jbesw** [comment]
I'm glad you managed to resolve this issue, and thanks for notifying me.
